[platformio]
default_envs = esp32-s3-devkitc-1

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 115200
monitor_speed = 115200

[env:nodemcuv2_ota_ap]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.4.1

[env:nodemcuv2_ota_sta]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = nodemcu-stepper.local

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM11
monitor_port = COM11
build_src_filter =
  -<*>
  +<main.cpp>
build_flags =
  -D STEPPER_DIR_PIN=16
  -D STEPPER_STEP_PIN=17
  -D STEPPER_M0_PIN=3
  -D STEPPER_M1_PIN=8
  -D STEPPER_M2_PIN=18
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-microservo-test]
extends = env:esp32-s3-devkitc-1
build_src_filter =
  -<*>
  +<main.cpp>
build_flags =
  ${env:esp32-s3-devkitc-1.build_flags}
  -D MICROSERVO_TEST_BUILD

[env:esp32-s3-servo-sweep-gpio10]
extends = env:esp32-s3-devkitc-1
upload_speed = 57600
build_src_filter =
  -<*>
  +<servo_sweep_gpio10.cpp>
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-arm-protocol-stub]
extends = env:esp32-s3-devkitc-1
upload_speed = 115200
build_src_filter =
  -<*>
  +<protocol_stub.cpp>

[env:esp32-s3-arm-protocol-stub-native-usb]
extends = env:esp32-s3-arm-protocol-stub
build_flags =
  ${env:esp32-s3-devkitc-1.build_flags}
  -D ARM_PROTOCOL_NATIVE_USB

[env:esp32-s3-arm-protocol-stub-usb-jtag]
extends = env:esp32-s3-arm-protocol-stub-native-usb
upload_protocol = esp-builtin
debug_tool = esp-builtin

[env:esp32-s3-arm-protocol-stub-freenove]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter =
  -<*>
  +<protocol_stub.cpp>
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-arm-controller]
extends = env:esp32-s3-devkitc-1
upload_speed = 57600
build_src_filter =
  -<*>
  +<arm_controller.cpp>
build_flags =
  ${env:esp32-s3-devkitc-1.build_flags}

[env:esp32-s3-arm-controller-native-usb]
extends = env:esp32-s3-arm-controller
build_flags =
  ${env:esp32-s3-arm-controller.build_flags}
  -D ARM_CONTROLLER_NATIVE_USB

[env:esp32-s3-arm-controller-usb-jtag]
extends = env:esp32-s3-arm-controller-native-usb
upload_protocol = esp-builtin
debug_tool = esp-builtin

[env:esp32-s3-arm-controller-freenove]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter =
  -<*>
  +<arm_controller.cpp>
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:as5048a_esp32_wrover]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM9
monitor_port = COM9
build_src_filter =
  -<*>
  +<as5048a_test.cpp>
